version: 1
validation: sovereign
accounts:
  - name: aaron1
    coins:
      - 200000000token
      - 200000000stake
  - name: aaron2
    coins:
      - 200000000token
      - 200000000stake
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: "stake"
validators:
  - name: aaron1
    bonded: 100000000stake
