version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    staking:
      params:
        bond_denom: "denom"
validators:
  - name: alice
    bonded: 100000000stake
